### ISSUE TITLE
Is this code the implement of Uncovering the structure of clinical EEG signals with self-supervised learning?

### ISSUE THREAD

**Issue by AllenLiang96** [Ouasfi/EEG-ssl#1]
hello, i am a master student interested in self-supervised learning in EEG. i have watched your code and found that your code seems like the implemention of the paper 'Uncovering the structure of clinical EEG signals with self-supervised learning', so i want to make sure if you are the author of the paper, so that i can learn the code under the assistance of the paper, thank you

**Comment by Ouasfi** [comment]
Hi, 
We are in fact working on a slightly different problem using the OpenMiir Dataset. But we have been inspired by this paper to implement Relative positioning. Their code is available here  [mberkeley/eeg-ssl](https://github.com/mlberkeley/eeg-ssl?fbclid=IwAR1mdQiu--6BPMHpwBTe6Pt6Uzve7h8pyEehz0z4_mbS_wqSivN-gYiQxBY). There are some differences in the way we sample  windows during training ( using a pytorch sampler allow to do it dynamically  ).

**Comment by AllenLiang96** [comment]
> Hi,
> We are in fact working on a slightly different problem using the OpenMiir Dataset. But we have been inspired by this paper to implement Relative positioning. Their code is available here [mberkeley/eeg-ssl](https://github.com/mlberkeley/eeg-ssl?fbclid=IwAR1mdQiu--6BPMHpwBTe6Pt6Uzve7h8pyEehz0z4_mbS_wqSivN-gYiQxBY). There are some differences in the way we sample windows during training ( using a pytorch sampler allow to do it dynamically ).

Thanks a lot for your reply and help.
